branchName: '${issue.number}'
branches:
  - label: 'ğŸš€ feature'
    prefix: 'feature/'
  - label: 'ğŸ”¨ refactor'
    prefix: 'feature/'
  - label: 'ğŸ› bug'
    prefix: 'fix/'
  - label: '*'
    prefix: 'feature/'
autoCloseIssue: true
autoLinkIssue: true
openDraftPR: true
commentMessage: 'Branch ${branchName} ë¡œ ìƒì„±ë˜ì—ˆì–´ìš” ğŸ‰'
