branchName: "${issue.number}"
branches:
  - label: "ğŸš€ feature"
    prefix: "feature/"
  - label: "ğŸ”¨ refactor"
    prefix: "feature/"
  - label: "ğŸ› bug"
    prefix: "fix/"
autoCloseIssue: true
